# Default values for contour.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Contour Deployment specific annotations
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8002"
  prometheus.io/path: "/stats/prometheus"

controller:
  image:
    repository: gcr.io/heptio-images/contour
    # Note that by default we use appVersion to get images tag
    # tag:
    pullPolicy: IfNotPresent
  # Enable statsd metrics
  statsd:
    enabled: false
  stats: {}
    # address: 0.0.0.0
    # port: 8002

proxy:
  image:
    repository: docker.io/envoyproxy/envoy-alpine
    tag: v1.9.1
    pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  loadBalancerIP: ""
  # Contour specific Service annotations
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  # This annotation puts the AWS ELB into "TCP" mode so that it does not
  # do HTTP negotiation for HTTPS connections at the ELB edge.
  # The downside of this is the remote IP address of all connections will
  # appear to be the internal address of the ELB. See docs/proxy-proto.md
  # for information about enabling the PROXY protocol on the ELB to recover
  # the original remote IP address.
  # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  # Due to the implementation of this feature, the source IP seen in the
  # target container is not the original source IP of the client. To enable
  # preservation of the client IP, the following fields can be configured in the
  # service spec (supported in GCE/Google Kubernetes Engine environments)
  # There are two available options: Cluster (default) and Local
  # externalTrafficPolicy: "Cluster"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# RBAC manifests management
rbac:
  enabled: true

nodeSelector: {}

tolerations: {}

# Enable and set Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
  minAvailable: null
