# Default values for contour.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

contour:
  image:
    repository: gcr.io/heptio-images/contour
    # Note that by default we use appVersion to get images tag
    # tag:
    pullPolicy: Always

envoy:
  image:
    repository: docker.io/envoyproxy/envoy-alpine
    tag: v1.7.0
    pullPolicy: IfNotPresent
# Contour specific Deployment annotations
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9001"
  prometheus.io/path: "/stats"
  prometheus.io/format: "prometheus"

service:
  type: LoadBalancer
  loadBalancerIP: ""
  # Contour specific Service annotations
  annotations: {}
  # This annotation puts the AWS ELB into "TCP" mode so that it does not
  # do HTTP negotiation for HTTPS connections at the ELB edge.
  # The downside of this is the remote IP address of all connections will
  # appear to be the internal address of the ELB. See docs/proxy-proto.md
  # for information about enabling the PROXY protocol on the ELB to recover
  # the original remote IP address.
  # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp

ingressRoutes:
  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

# RBAC manifests management
rbac:
  enabled: true

nodeSelector: {}

tolerations: {}
