## Weaveworks Scope image version
## ref: https://hub.docker.com/r/weaveworks/scope/tags/
##
imageTag: 1.6.5

## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: "IfNotPresent"

## Weave Scope cloud token
## ref: https://github.com/bitnami/bitnami-docker-redis#setting-the-server-password-on-first-run
##
# serviceToken: ""

## Scope app resource limits
cpuApp: 500m
memoryApp: 500Mi

## Scope probe resource limits
cpuProbe: 100m
memoryProbe: 150Mi

## Kubernetes service type:
## LoadBalancer or ClusterIP
serviceType: LoadBalancer
